### ISSUE TITLE
remove log.Fatal and use Log.panic instead

### ISSUE THREAD

**Issue by leofigy** [pitakill/azure_resources#1]
Issue with the log.Fatal if we use your code as a library it will do a os.Exit
in the caller but that is not recoverable. 

so use log.Panic instead

**Comment by pitakill** [comment]
A better usage for this is a return of the error. Because that method is reachable from outside.

I see the merge of the https://github.com/pitakill/azure_resources/pull/2, I'm going to update the auto generation of the file with the changes, because the `main.go` file is auto generated ;-)

**Comment by leofigy** [comment]
yea agree with that , an error would be better, but without network connectivity orbital fails right now , also :) added this PRhttps://github.com/thetonymaster/orbital-module-azurerm/pull/4018.09.2019, 15:44, "Leopoldo Caballero" <notifications@github.com>:A better usage for this is a return of the error. Because that method is reachable from outside.
I see the merge of the #2, I'm going to update the auto generation of the file with the changes, because the main.go file is auto generated ;-)

**Comment by pitakill** [comment]
This is addressed with https://github.com/pitakill/azure_resources/pull/3
